DELETE FROM `provinsi` WHERE `id`='11';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('11', 'Aceh');
DELETE FROM `provinsi` WHERE `id`='12';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('12', 'Sumatera Utara');
DELETE FROM `provinsi` WHERE `id`='13';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('13', 'Sumatera Barat');
DELETE FROM `provinsi` WHERE `id`='14';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('14', 'Riau');
DELETE FROM `provinsi` WHERE `id`='15';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('15', 'Jambi');
DELETE FROM `provinsi` WHERE `id`='16';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('16', 'Sumatera Selatan');
DELETE FROM `provinsi` WHERE `id`='17';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('17', 'Bengkulu');
DELETE FROM `provinsi` WHERE `id`='18';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('18', 'Lampung');
DELETE FROM `provinsi` WHERE `id`='19';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('19', 'Kepulauan Bangka Belitung');
DELETE FROM `provinsi` WHERE `id`='21';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('21', 'Kepulauan Riau');
DELETE FROM `provinsi` WHERE `id`='31';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('31', 'DKI Jakarta');
DELETE FROM `provinsi` WHERE `id`='32';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('32', 'Jawa Barat');
DELETE FROM `provinsi` WHERE `id`='33';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('33', 'Jawa Tengah');
DELETE FROM `provinsi` WHERE `id`='34';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('34', 'DI Yogyakarta');
DELETE FROM `provinsi` WHERE `id`='35';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('35', 'Jawa Timur');
DELETE FROM `provinsi` WHERE `id`='36';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('36', 'Banten');
DELETE FROM `provinsi` WHERE `id`='51';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('51', 'Bali');
DELETE FROM `provinsi` WHERE `id`='52';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('52', 'Nusa Tenggara Barat');
DELETE FROM `provinsi` WHERE `id`='53';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('53', 'Nusa Tenggara Timur');
DELETE FROM `provinsi` WHERE `id`='61';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('61', 'Kalimantan Barat');
DELETE FROM `provinsi` WHERE `id`='62';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('62', 'Kalimantan Tengah');
DELETE FROM `provinsi` WHERE `id`='63';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('63', 'Kalimantan Selatan');
DELETE FROM `provinsi` WHERE `id`='64';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('64', 'Kalimantan Timur');
DELETE FROM `provinsi` WHERE `id`='65';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('65', 'Kalimantan Utara');
DELETE FROM `provinsi` WHERE `id`='71';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('71', 'Sulawesi Utara');
DELETE FROM `provinsi` WHERE `id`='72';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('72', 'Sulawesi Tengah');
DELETE FROM `provinsi` WHERE `id`='73';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('73', 'Sulawesi Selatan');
DELETE FROM `provinsi` WHERE `id`='74';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('74', 'Sulawesi Tenggara');
DELETE FROM `provinsi` WHERE `id`='75';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('75', 'Gorontalo');
DELETE FROM `provinsi` WHERE `id`='76';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('76', 'Sulawesi Barat');
DELETE FROM `provinsi` WHERE `id`='81';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('81', 'Maluku');
DELETE FROM `provinsi` WHERE `id`='82';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('82', 'Maluku Utara');
DELETE FROM `provinsi` WHERE `id`='91';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('91', 'Papua Barat');
DELETE FROM `provinsi` WHERE `id`='92';
INSERT INTO `provinsi` (`id`, `nama`) VALUES ('92', 'Papua');
